### ISSUE TITLE
Setup metrics scraping for all apps

### ISSUE THREAD

**Issue by lorenzo-w** [lorenzo-w/civi-cloud#32]
- [ ] Nextcloud:

```yaml
metrics.enabled: true
metrics.serviceMonitor.enabled: true
```

- [ ] Rocket.Chat:

```yaml
serviceMonitor.enabled: true
```

- [ ] Wordpress:

```yaml
metrics.enabled: true
metrics.serviceMonitor.enabled: true
```

- [ ] Jitsi:

```yaml
jvb:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
```
